async function loadData(){const r=await fetch('data/dashboard.json');if(!r.ok)throw new Error('dashboard data missing');return r.json()}
const el=(tag,cls,html)=>{const node=document.createElement(tag);if(cls)node.className=cls;if(html!==undefined)node.innerHTML=html;return node};
function render(d){
  document.querySelector('#run-status').textContent=d.run.status.toUpperCase();document.querySelector('#provider').textContent=d.run.provider;document.querySelector('#validation-status').textContent=d.validation.status;
  const kpis=[['150','historical items','137 posts • 13 videos'],['90.0%','promotional mix','Observed baseline'],['2.2×','education save-rate ratio','Directional association'],['66.02%','extreme video ER','Outlier preserved']];
  const kg=document.querySelector('#kpis');kpis.forEach(x=>kg.append(el('div','kpi',`<strong>${x[0]}</strong><span>${x[1]}</span><small>${x[2]}</small>`)));
  const audit=[['Missing CTAs',d.audit.missing_by_column.cta],['Wrong-handle rows',d.audit.aristostyling_rows],['Video views > reach',d.facts.video_views_exceed_reach_count],['Duplicate IDs',d.audit.duplicate_ids],['Span',`${d.audit.span_days} days`]];
  const al=document.querySelector('#audit-list');audit.forEach(x=>al.append(el('div','',`<span>${x[0]}</span><b>${x[1]}</b>`)));
  const mg=document.querySelector('#metric-grid');Object.entries(d.metric_contract.metrics).slice(0,9).forEach(([k,v])=>mg.append(el('div','metric',`<b>${k.replaceAll('_',' ')}</b><code>${v}</code>`)));
  document.querySelector('#diagnosis-text').textContent=d.diagnosis.selected_diagnosis;document.querySelector('#diagnosis-caveat').textContent=d.diagnosis.outlier_caveat;
  const sg=document.querySelector('#strategy-cards');d.strategy.evidence_linked_changes.forEach(c=>sg.append(el('article','strategy-card',`<span class="id">${c.evidence}</span><h3>${c.strategy_change}</h3><p>${c.finding}</p><small>${c.confidence_or_limitation}</small>`)));
  const pg=document.querySelector('#plan-cards');d.plan.forEach(p=>pg.append(el('article',`plan-card ${p.format}`,`<div class="day"><span>DAY ${p.day}</span><span>${p.format.toUpperCase()}</span></div><h3>${p.hook}</h3><p>${p.content_idea}</p><span class="kpi-chip">${p.primary_kpi}</span>`)));
  const cg=document.querySelector('#creative-gallery');d.plan.filter(p=>p.format==='post').forEach(p=>cg.append(el('article','creative-card',`<img src="../assets/posts/${p.asset_filename}" alt="${p.hook}"><div>DAY ${p.day} • ${p.topic}</div>`)));
  const vg=document.querySelector('#video-gallery');d.plan.filter(p=>p.format==='video').forEach(p=>{const stem=p.asset_filename.replace(/\.mp4$/,'');vg.append(el('article','video-card',`<video controls muted playsinline preload="metadata" poster="../assets/video_frames/${stem}_preview.png"><source src="../assets/videos/${p.asset_filename}" type="video/mp4"></video><div><div class="eyebrow lime">DAY ${p.day} • VIDEO</div><h3>${p.hook}</h3><p>${p.full_proposed_caption}</p><span class="badge dark-badge">${p.reasoned_target_range}</span></div>`))});
  const comp=document.querySelector('#comparison-grid');d.before_after.forEach(c=>comp.append(el('article','comparison-card',`<small>${c.dimension}</small><h3>${c.before}</h3><div class="arrow">↓</div><b>${c.after}</b>`)));
  const tr=document.querySelector('#trace');d.trace.slice(-11).forEach(t=>tr.append(el('div','trace-row',`<b>${t.agent}</b><span>${t.decision_summary}</span><span>${t.status}</span>`)));
  document.querySelector('#validation-score').textContent=`${d.validation.passed}/${d.validation.passed+d.validation.failed}`;document.querySelector('#validation-heading').textContent=d.validation.status==='PASS'?'Production gate passed.':'Repair gate active.';
}
loadData().then(render).catch(e=>{document.querySelector('#validation-heading').textContent=e.message;console.error(e)});
const sections=[...document.querySelectorAll('main section[id]')],links=[...document.querySelectorAll('#nav a')];const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${entry.target.id}`))}}),{rootMargin:'-20% 0px -65% 0px'});sections.forEach(s=>observer.observe(s));
